name: Deploy backend/ to serv00

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERV00_KEY }}

      - name: Show backend directory structure (for debug)
        run: ls -lR ./backend

      - name: Rsync backend/api and backend/utils/ to serv00
        run: |
          rsync -avz --delete \
            --exclude='config.php' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./backend/api/ "${{ secrets.SERV00_USER }}@${{ secrets.SERV00_HOST }}:${{ secrets.SERV00_PATH }}/api/"
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./backend/utils/ "${{ secrets.SERV00_USER }}@${{ secrets.SERV00_HOST }}:${{ secrets.SERV00_PATH }}/utils/"
